data:
  raw_path: data/raw/household_power_consumption.csv
  processed_path: data/processed/cleaned_data.csv
  target_column: Global_active_power

split:
  test_size: 0.2
  random_state: 42

features:
  datetime_column:
    date: Date
    time: Time

model:
  type: linear_regression

training:
  epochs: 1
